/*
  02. MODIFICAR LA COMISION DE LOS VENDEDORES AL 2% SOLAMENTE
  A LOS QUE TENGAN UN SUELDO MAYOR DE 50 000
*/
SELECT * FROM vendedores WHERE sueldo > 50000;
UPDATE vendedores SET comision = 0.5 WHERE sueldo >= 50000;



