# Consulta con una condicion
SELECT * FROM usuarios WHERE email = 'axel@axel.com';

# MOSTRAR NOMBRE Y APELLIDOS DE PERSONAS REGISTRADAS EN 2019 #

SELECT nombre,apellidos FROM usuarios WHERE YEAR(fecha_registro) = 2018;

# MOSTRAR NOMBRE Y APELLIDOS DE PERSONAS NO REGISTRADAS EN 2018
SELECT nombre,apellidos FROM usuarios WHERE YEAR(fecha_registro) != 2018 OR ISNULL(fecha_registro);

# 3. MOSTRAR EL EMAIL DE LOS USUARIOS CUYO APELLIDO CONTENGA LA LETRA A Y QUE LA CONTRASEÑA SEA 1234
SELECT email FROM usuarios WHERE apellidos LIKE '%a%' AND password = '1234';

#4. MOSTRAR TODOS LOS REGISTROS DE LA TABLA USUARIOS CUYO AÑO DE REGISTRO SEA PAR
SELECT * FROM usuarios WHERE (YEAR(fecha_registro)%2 = 0);
# 5. SACAR TODOS LOS REGISTROS DE LA TABLA USUARIOS CUYO NOMBRE TENGA MAS DE 5 LETRAS Y QUE SE HAYAN REGISTRADO ANTES DE 2018 Y MOSTRAR EL NOMBRE EN MAYUSCULAS
SELECT UPPER (nombre) AS 'Nombre',apellidos FROM usuarios WHERE (LENGTH(nombre) > 5) AND (YEAR(fecha_registro) < 2018);